### ISSUE TITLE
Doesn't seem possible to search by usage rights

### ISSUE THREAD

**Issue by cuibonobo** [ArchiveLabs/archive.org#3]
I've tried searching under the `licenseurl`, `usage`, and `rights_license_url` custom fields for the [CC0](http://creativecommons.org/publicdomain/zero/1.0/) URL, but I keep getting zero results. This license type is used by thousands of items on Archive.org, so something seems wrong.

**Comment by jjjake** [comment]
@cuibonobo I bet it's the `/` in the query that's causing this issue for you. Try escaping them with `\`, for example: `licenseurl:(*creativecommons.org\/publicdomain\/zero\/1.0*)`

https://archive.org/search.php?query=licenseurl%3A%28%2Acreativecommons.org%5C%2Fpublicdomain%5C%2Fzero%5C%2F1.0%2A%29

**Comment by cuibonobo** [comment]
🙌 Good catch. Thanks.
