### ISSUE TITLE
Provide Ability to Specify a URL instead of a filename in IA Upload

### ISSUE THREAD

**Issue by joffemd** [ArchiveLabs/archive.org#5]
If the file name parameter begins with http:// , https:// , or ftp:// the application should download the file, get the local file name and then upload it to the Archive.

**Comment by mekarpeles** [comment]
cc: @jjjake -- this is a fairly commonly requested feature.
@joffemd you can accomplish this also by using wget (in the meantime)

**Comment by jjjake** [comment]
This would be a really convenient feature! However, after talking to one of our senior engineers, I don't think it's something we would want to support. It sounds like a simple idea, but doing it right would take quite a bit of work that we can't currently prioritize.

I would recommend using something like wget and uploading with `ia upload --delete ...`, if you're limited on disk space. Please email me  or talk to me on the ArchiveLabs slack, if you need any help with your workflow.

I appreciate the suggestion. Thank you, @joffemd!

**Comment by mekarpeles** [comment]
Tagging this as an issue for internetarchive tool:
